ToDo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('todo.urls')),
]

todo/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^add_todo', 'todo.views.add_todo', name='add_todo'),
    url(r'^delete_todo/(?P<todo_id>\d+)', 'todo.views.delete_todo', name='delete_todo'),
    url(r'^profile/delete_todo/(?P<todo_id>\d+)', 'todo.views.delete_todo_profile', name='delete_todo_profile'),
    url(r'^delete_trash/(?P<todo_id>\d+)', 'todo.views.delete_trash', name='delete_trash'),
    url(r'^edit_todo/', 'todo.views.edit_todo', name='edit_todo'),
    url(r'^profile/edit_todo/', 'todo.views.edit_todo_profile', name='edit_todo_profile'),
    url(r'^get_user/(?P<user_id>\d+)', 'todo.views.get_user', name='get_user'),
    url(r'^profile', 'todo.views.profile', name='profile'),
    url(r'^', 'todo.views.home', name='home')
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class ToDo(models.Model):
	title = models.CharField(max_length=100)
	desc = models.CharField(max_length=1000)
	creator = models.ForeignKey(User, related_name="todos")
	is_deleted = models.BooleanField(default=False)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = "TODOs"

	def __str__(self):
		return self.title

todo/forms.py
from django.forms import ModelForm
from todo.models import ToDo

class ToDoForm(ModelForm):
	class Meta:
		model = ToDo
		exclude = ('creator', 'is_deleted')
		

todo/views.py
import json
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from todo.models import ToDo
from todo.forms import ToDoForm
from django.contrib.auth.models import User

def delete_db_entry(id):
	try:
		todo_to_delete = ToDo.objects.filter(pk=id)
		todo_to_delete.update(is_deleted=True)
	except ToDo.DoesNotExist:
		# todo doesn't exist with the given id, do nothing.
		pass


def get_profile_data(todos):
	pending_todos = todos.exclude(is_deleted=True).order_by('-created_at')
	deleted_todos = todos.filter(is_deleted=True).order_by('-updated_at')
	return (pending_todos, deleted_todos)


def home(request):
	todos = ToDo.objects.all().order_by('-created_at').exclude(is_deleted=True)
	return render_to_response('todos.html', {'todos': todos}, context_instance=RequestContext(request))


def delete_todo(request, todo_id):
	delete_db_entry(todo_id)
	return HttpResponseRedirect('/')


def delete_todo_profile(request, todo_id):
	delete_db_entry(todo_id)
	return HttpResponseRedirect('/profile')


@login_required
def add_todo(request):
	if request.is_ajax() and request.method == "POST":
		form = ToDoForm(request.POST)
		if form.is_valid():
			title = request.POST.get('title')
			desc = request.POST.get('desc')
			ToDo.objects.create(
				title=title, desc=desc, creator=request.user
			)
			return HttpResponse(json.dumps({"success": "Form submitted succesfully !", "redirect_to": '/'}))
		else:
			return HttpResponse(json.dumps({"error": form.errors}))
	else:
		form = ToDoForm()
	return render_to_response('add_todo_form.html', {'form': form}, context_instance=RequestContext(request))


def edit_todo_helper(request_obj, todo_id, redirect_to=''):
	todo = ToDo.objects.filter(pk=todo_id).exclude(is_deleted=True)
	if request_obj.is_ajax() and request_obj.method == "POST":
		form = ToDoForm(request_obj.POST)
		if form.is_valid():
			title = request_obj.POST.get('title')
			desc = request_obj.POST.get('desc')
			todo.update(title=title, desc=desc)
			return HttpResponse(json.dumps({"success": "Form submitted succesfully !", "redirect_to": '/' + redirect_to}))
		else:
			return HttpResponse(json.dumps({"error": form.errors}))
	else:
		form = ToDoForm(initial={'title': todo[0].title, 'desc': todo[0].desc})
	return render_to_response('add_todo_form.html', {'form': form, 'action': 'edit_todo/' + str(todo_id)}, 
									   context_instance=RequestContext(request_obj))


@login_required
def edit_todo(request):
	if request.method == "GET":
		todo_id = request.GET.get('id')
	else:
		todo_id = request.POST.get('id')
		print(todo_id)
	return edit_todo_helper(request, todo_id)


@login_required
def edit_todo_profile(request, todo_id):
	if request.method == "GET":
		todo_id = request.GET.get('id')
	else:
		todo_id = request.POST.get('id')
	return edit_todo_helper(request, todo_id, 'profile')


@login_required
def profile(request):
	todos = ToDo.objects.filter(creator=request.user)
	pending_todos, deleted_todos = get_profile_data(todos)
	return render_to_response('profile.html', {'todos': pending_todos, 'deleted_todos': deleted_todos}, 
							   context_instance=RequestContext(request))


def delete_trash(request, todo_id):
	try:
		todo_to_delete = ToDo.objects.get(pk=todo_id)
		todo_to_delete.delete()
	except ToDo.DoesNotExist:
		# todo doesn't exist with the given id, do nothing.
		pass
	return HttpResponseRedirect('/profile')


def get_user(request, user_id):
	try:
		user = User.objects.get(pk=user_id)
		todos = ToDo.objects.filter(creator=user_id)
		pending_todos, deleted_todos = get_profile_data(todos)
		if user == request.user:
			return HttpResponseRedirect('/profile')
	except User.DoesNotExist:
		pass
	return render_to_response('profile.html', {'todos': pending_todos, 'deleted_todos': deleted_todos, 'diff_user': True, 'cur_user': user}, 
							  context_instance=RequestContext(request))

templates/add_todo_form.html
{% if action %}
<h6 class="right-align header-text">Edit Task</h6>
{% else %}
<h6 class="right-align header-text">Add Task</h6>
{% endif %}
<div class="error-area center">
	
</div>

{% if action %}
<form method="post" action="{{ action }}" id="edit_todo_form">
{% else %}
<form method="post" action="/add_todo/" id="add_todo_form">
{% endif %}
	{% csrf_token %}
	<div class="input-field">
	    <label for="id_title">Title</label>
	    {{ form.title }}
	</div>
	<div class="input-field">
	    <label for="id_desc">Description</label>
	    {{ form.desc }}
	</div>
	<div class="right-align">
		{% if action %}
		<button class="btn btn-flat waves-effect waves-light blue" type="submit">Save changes</button>
		{% else %}
		<button class="btn btn-flat waves-effect waves-light blue" type="submit">add</button>
		{% endif %}
	</div>
</form>

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
        <title>TO-D0 APP</title>

        <!-- CSS  -->

        <link href="{% static 'assets/css/materialize.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="{% static 'assets/css/ionicons.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="{% static 'assets/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    </head>


    <body>
        <div class="navbar-fixed">
            <nav>
                <div class="container">
                    <a href="/" class="brand-logo">TASK-MANAGER</a>
                    <ul class="right hide-on-med-and-down">
                        {% if user.is_authenticated %}
                            <li><a href="/profile/">{{ user.get_full_name }}</a></li>
                            <li><a href="/logout/">logout</a></li>
                        {% else %}
                            <li><a href="/login/">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>


        <div class="container" id="body-container">
            <div class="section">
                {% block header %}
                {% endblock %}
                {% block page_content %}
                {% endblock %}
            </div>
        </div>


        <!--  Scripts-->
        <script src="{% static 'assets/js/jquery.js' %}"></script>
        <script src="{% static 'assets/js/materialize.min.js' %}"></script>
        <script src="{% static 'assets/js/scripts.js' %}"></script>
    </body>
</html>

templates/login.html
{% extends 'index.html' %}


{% block page_content %}
<div class="center">
	<div class="row">
		<div class="col l6 m12 s12 offset-l3">
			<div class="card" id="center-div">
				<div class="card-content">
					<h6 class="right-align header-text">sign in</h6>
					{% if form.errors %}
			    	<p style="color: #d50000" class="news-title">
			    		<i class="ion-close-circled"></i> 
			    		Your username and password didn't match. Please try again.
			    	</p>
			    	{% endif %}
					
					<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
					{% csrf_token %}
						<div class="input-field">
						    <label for="id_username">username</label>
						    <input id="id_username" maxlength="254" name="username" type="text"/>
						</div>
						<div class="input-field">
						    <label for="id_password">password</label>
						    <input id="id_password" name="password" type="password"/>
						</div>

						<div class="right-align">
							<button class="btn btn-flat waves-effect waves-light blue" type="submit">login</button>
						</div>
						<input type="hidden" name="next" value="{{ next }}" />
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/profile.html
{% extends 'index.html' %}
{% block page_content %}
	{% if diff_user %}
	<h6 class="header-text">{{ cur_user.get_username }}'s pending tasks</h6>
	{% else %}
	<h6 class="header-text">your pending tasks</h6>
	{% endif %}
	<div class="row">
		{% if todos %}
			{% for todo in todos %}
				<div class="col l4 m6 s12">
					<div class="card">
						<div class="card-content">
						    <h6 class="title news-headline">{{ todo.title }}</h6>
						    <h6 class="news-title">Pending | {{ todo.created_at }}</h6>
						    <p class="news-text">{{ todo.desc }}</p>
						</div>
						{% if not diff_user %}
						<div class="card-action">
		                	<a href="/profile/delete_todo/{{ todo.id }}/"><i class="ion-checkmark-circled"></i> Mark as Done</a>
		                	<a href="/profile/edit_todo/{{ todo.id }}/" class="edit-todo"><i class="ion-edit"></i> Edit</a>
			            </div>
						{% endif %}
			        </div>
				</div>
			{% endfor %}
		{% else %}
			<div class="col l12 m6 s12">
				<div class="card-panel title news-headline center-align">
					No tasks to show!!
				</div>
			</div>
		{% endif %}
	</div>

	<h6 class="header-text">recently completed tasks</h6>
	<div class="row">
		{% if deleted_todos %}
			{% for todo in deleted_todos %}
				<div class="col l4 m6 s12">
					<div class="card">
						<div class="card-content">
						    <h6 class="title news-headline">{{ todo.title }}</h6>
						    <h6 class="news-title">completed | {{ todo.updated_at }}</h6>
						    <p class="news-text">{{ todo.desc }}</p>
						</div>
						{% if not diff_user %}
						<div class="card-action">
		                	<a href="/delete_trash/{{ todo.id }}/"><i class="ion-trash-b"></i> Delete</a>
			            </div>
			            {% endif %}
			        </div>
				</div>
			{% endfor %}
		{% else %}
				<div class="col l12 m6 s12">
					<div class="card-panel title news-headline center-align">
						No tasks to show!!
					</div>
				</div>
		{% endif %}
	</div>

	<!-- Modal Structure -->
	<div id="modal1" class="modal">
		<a href="#!" class="modal-close" id="close-modal">&#10006</a>
	    <div class="modal-content">
	        <!-- Form to be loaded dynamically -->
	    </div>
	</div>
{% endblock %}

templates/todos.html
{% extends 'index.html' %}
{% block page_content %}
	<div class="row">
		{% for todo in todos %}
			<div class="col l4 m6 s12">
				<div class="card">
					<div class="card-content">
					    <h6 class="title news-headline">{{ todo.title }}</h6>
					    <h6 class="news-title">
					    	<a href="/get_user/{{ todo.creator.id }}/" class="news-title">
					    	<i class="ion-android-person"></i> {{ todo.creator.get_full_name }}
					    	</a> 
					    	<b>|</b> {{ todo.created_at }}
					    	</h6>
					    <p class="news-text">{{ todo.desc }}</p>
					</div>
					<div class="card-action">
						{% if user.is_authenticated and todo.creator == user %}
		                	<a href="/delete_todo/{{ todo.id }}/"><i class="ion-checkmark-circled"></i> Mark as Done</a>
			                <a href="/edit_todo/{{ todo.id }}/" class="edit-todo" data-id="{{ todo.id }}"><i class="ion-edit"></i> Edit</a>
		                {% else %}
		                	<a class="disabled tooltipped" data-position="bottom" data-delay="50" 
		                	   data-tooltip="You are not authorized to mark this task!"><i class="ion-checkmark-circled"></i> Mark as Done</a>
		                	<a class="disabled tooltipped" data-position="bottom" data-delay="50" 
		                	   data-tooltip="You are not authorized to edit this task!"><i class="ion-edit"></i> Edit</a>
		                {% endif %}
		            </div>
		        </div>
			</div>
		{% endfor %}
	</div>
	{% if user.is_authenticated %}
	<a href="add_todo" class="btn-floating btn-large waves-effect waves-light fixed-element tooltipped"
	   data-position="left" data-delay="50" data-tooltip="Add a new task?">
		<i class="ion-plus"></i>
	</a> 
	{% endif %}

	<!-- Modal Structure -->
	<div id="modal1" class="modal">
		<a href="#!" class="modal-close" id="close-modal">&#10006</a>
	    <div class="modal-content">
	        <!-- Form to be loaded dynamically -->
	    </div>
	</div>  
{% endblock %}